ppoker_fin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
]

tasks/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('tasks_main_page', views.tasks_main_page, name="tasks_main_page"), # tasks

    path('my_tasks_page', views.my_tasks, name="my_tasks_page"), # tasks/my
    path('tasks_update_page/<str:pk>', views.tasks_update, name="tasks_update_page"), # tasks/<str:pk>/update
    path('tasks_delete_page/<str:pk>', views.tasks_delete, name="tasks_delete_page"), # tasks/<str:pk>/delete
    path('task_detail_page/<str:pk>', views.task_detail, name="task_detail_page"), # tasks/<str:pk>/
    path('task/<str:pk>/estimate/<str:est_id>', views.estimate_task, name='estimate_task'), # tasks/<str:pk>/estimates/<str:est_id>

    path('estimate-task-create/<int:pk>', views.estimate_task_create, name="estimate-task-create"), # tasks/<int:pk>/estimates

]

tasks/models.py
from django.db import models
from sprints.models import Sprint
from django.contrib.auth.models import User


class Task(models.Model):
    """Model of Task"""

    title = models.CharField(max_length=150, help_text='Title of the task')
    description = models.TextField(help_text='Description of the task')
    created_at = models.DateField(auto_now_add=True, help_text='Date of creation of the task')
    product_owner = models.ForeignKey(User, max_length=150, on_delete=models.CASCADE, null=True,
                                      help_text='Product owner of the task', related_name='owned_tasks')
    user_story = models.CharField(max_length=5, help_text='User story number', null=True, blank=True)
    created_by = models.ForeignKey(User, max_length=150, on_delete=models.CASCADE, null=True,
                                   help_text='User who created the task', related_name='created_tasks')
    sprint = models.ForeignKey(Sprint, max_length=150, on_delete=models.CASCADE, null=True, related_name='tasks')
    estimation_ended = models.BooleanField(default=False)


class TaskEstimation(models.Model):
    """model of task estimation"""

    ESTIMATION_CHOICES = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "5"),
        ("5", "8"),
        ("6", "13"),
        ("7", "21"),
    )

    estimation = models.CharField(choices=ESTIMATION_CHOICES, max_length=150)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, help_text='Who estimated the task',
                             related_name='estimations', null=False)
    created_at = models.DateField(auto_now_add=True, help_text='Date of task estimation')
    estimated_by = models.ForeignKey(User, max_length=150, on_delete=models.CASCADE, null=True,
                                     help_text='User who estimated the task', related_name='estimations')

    class Meta:
        """Connecting task with the estimators"""
        unique_together = ('task', 'estimated_by')

    def __str__(self):
        # return estimation value from the ESTIMATED_CHOICES dict by they key
        # from number position of the scroll bar"
        choices_dict = dict(self.ESTIMATION_CHOICES)
        if self.estimation in choices_dict:
            return choices_dict[self.estimation]
        else:
            return f'{self.estimation, self.estimated_by.get_full_name()}'

tasks/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import PasswordInput, TextInput
from . models import Task, TaskEstimation


class TaskForm(ModelForm):
    """bulidning task form"""
    class Meta:
        """Task spec"""
        model = Task
        fields = ['title', 'description', 'product_owner', 'user_story', 'sprint',]


class TaskEstimationForm(forms.ModelForm):
    """Building estimation form """
    class Meta:
        """Fields for estiamtion"""
        model = TaskEstimation
        fields = ['estimation']

    def __init__(self, *args, **kwargs):
        self.task = kwargs.pop('task', None)
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        #     czy to zapewni poprawne działanie formularza opartego na args i kwargs?

    def save(self, commit=True):
        estimation = super().save(commit=False)
        estimation.task = self.task  # Ustawienie pola task
        if commit:
            estimation.save()
        return estimation

tasks/views.py
from django.http import HttpResponse, HttpRequest
from typing import Dict, Any
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Min, Max
from .models import Task, TaskEstimation
from .forms import TaskEstimationForm, TaskForm
from sprints.models import Sprint


def tasks_main_page(request: HttpRequest) -> HttpResponse:
    """Task main page view. Renders the main tasks page."""
    return render(request, 'tasks/tasks_main_page.html')


def my_tasks(request: HttpRequest) -> HttpResponse:
    """View that shows the list of tasks"""
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.created_by = request.user
            task.save()
            return redirect('my_tasks_page')
    sprints_user_is_in = Sprint.objects.filter(users=request.user)
    tasks = Task.objects.filter(sprint__in=sprints_user_is_in)
    # tasks = Task.objects.filter(created_by=request.user) # TODO.
    paginator = Paginator(tasks, 3)
    page_number = request.GET.get('page')

    try:
        tasks_page = paginator.page(page_number)
    except PageNotAnInteger:
        tasks_page = paginator.page(1)
    except EmptyPage:
        tasks_page = paginator.page(paginator.num_pages)

    context: Dict[str, Any] = {
        'create_task_form': form,
        'list_tasks': tasks_page
    }

    return render(request, 'tasks/my_tasks_page.html', context)


def tasks_update(request: HttpRequest, pk: int) -> HttpResponse:
    """Task update view"""
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        else:
            return redirect('dashboard')

    context: Dict[str, Any] = {'UpdateTaskForm': form}
    return render(request, 'tasks/tasks_update_page.html', context)


def tasks_delete(request, pk):
    """Delete task view"""
    task = Task.objects.get(id=pk)

    if request.method == 'POST':
        task.delete()
        return redirect('my_tasks_page')

    return render(request, 'tasks/tasks_delete_page.html')


def task_detail(request, pk):
    # """Task for detail view by its id """
    # task = get_object_or_404(Task, id=pk)
    # estimations = TaskEstimation.objects.filter(task=task)
    # assigned_users = task.sprint.users.all() if task.sprint else []
    # context = {
    #     'task': task,
    #     'assigned_users': assigned_users,
    #     'estimations': estimations,
    # }
    # return render(request, 'tasks/task_detail_page.html', context)
    task = get_object_or_404(Task, id=pk)
    estimations = TaskEstimation.objects.filter(task=task)
    assigned_users = task.sprint.users.all() if task.sprint else []
    average_estimation = None

    # estimation_ended = False
    if task.sprint and len(estimations) == len(assigned_users):

        estimation_values = {
            "1": 1, "2": 2, "3": 3, "4": 5,
            "5": 8, "6": 13, "7": 21
        }
        total_estimation = sum(estimation_values[est.estimation] for est in estimations)
        average_estimation = total_estimation /len(estimations)

        estimations_list = [estimation_values[est.estimation] for est in estimations]
        if max(estimations_list) - min(estimations_list) <= 5:
            # estimation_ended = True
            # if estimation_ended:
            task.estimation_ended = True
            task.save()
    context = {
        'task': task,       
        'estimations': estimations,
        'assigned_users': assigned_users,
        'estimation_ended': task.estimation_ended,
        'average_estimation': average_estimation
    }
    return render(request, 'tasks/task_detail_page.html', context)







def estimate_task(request, pk: int, est_id: int):
    """Task estimation View with possible estimation overwrite"""
    task = get_object_or_404(Task, id=pk)

    # try:
    estimation = TaskEstimation.objects.get(task=task, id=est_id, estimated_by=request.user)
    # except TaskEstimation.DoesNotExist:
    #     estimation = None

    if request.method == 'POST':
        form = TaskEstimationForm(request.POST, task=task, user=request.user)
        if form.is_valid():
            if estimation:

                estimation.estimation = form.cleaned_data['estimation']
                estimation.save()
            else:

                estimation = form.save(commit=False)
                estimation.task = task
                estimation.estimated_by = request.user
                estimation.save()
            return redirect('task_detail_page', pk=pk)
    else:

        if estimation:
            form = TaskEstimationForm(instance=estimation, task=task, user=request.user)
        else:
            form = TaskEstimationForm(task=task, user=request.user)

    context = {
        'form': form,
        'task': task,
        'estimation': estimation,
        'estimated_by': estimation.estimated_by if estimation else None,
    }

    return render(request, 'tasks/estimate_task.html', context)


def estimate_task_create(request, pk: int):
    task = get_object_or_404(Task, id=pk)
    if request.method == 'POST':
        form = TaskEstimationForm(request.POST, task=task, user=request.user)
        if form.is_valid():
            estimation = form.save(commit=False)
            estimation.user = request.user
            estimation.save()
            return redirect('task_detail_page', pk=pk)
    else:
        form = TaskEstimationForm(task=task, user=request.user)

    context = {
        'form': form,
    }
    return render(request, 'tasks/estimate-task-create.html', context)

tasks/templates/tasks/create_task.html
{%  extends 'users/navbar.html'  %}
{%  block content%}
    <div class="container">
        <h1> creating the task </h1>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{ CreateTaskForm.as_p }}
            <br>
            <button type="submit"> Create task    </button>
        </form>
        <a href="{%  url 'user_logout' %}"> </a>
    </div>
{% endblock %}

tasks/templates/tasks/estimate-task-create.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Estimation</button>
</form>

tasks/templates/tasks/estimate_task.html
{% extends 'users/navbar.html'  %}
{% block content %}
  <h2>Task estimated: {{ task.title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm Story points</button>
  </form>

  {% if estimation %}
    <h2>Your last estimation: {{ estimation }}</h2>
  {% else %}
    <p>No estimations made yet.</p>
  {% endif %}
{% endblock %}

tasks/templates/tasks/my_tasks_page.html
{%  extends 'users/navbar.html'  %}
{%  block content   %}
    <h1>My tasks </h1>
    <br>
    {%  for task in list_tasks %}
    <div class="container">
        <br>
        <a href="{% url 'task_detail_page' task.pk %}" target="_blank">{{ task.title }}</a>
        <br>
        {{task.description}}
        <br>
        {{task.created_at}}
        <br>
        {{task.product_owner}}
        <br>
        {{task.user_story}}
        <br>
        {{task.created_by}}
        <br>
        {{task.sprint}}
        <br>
        <a href="{% url 'tasks_update_page' task.id %}">Update task</a>
        <br>
        <a href="{% url 'tasks_delete_page' task.id %}">Delete task</a>
        <br>
    </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if list_tasks.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ list_tasks.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ list_tasks.number }} of {{ list_tasks.paginator.num_pages }}.
            </span>
            {% if list_tasks.has_next %}
                <a href="?page={{ list_tasks.next_page_number }}">next</a>
                <a href="?page={{ list_tasks.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ create_task_form.as_p }}
        <button type="submit">Create Task</button>
    </form>
{% endblock %}

tasks/templates/tasks/task_detail_page.html
{% extends 'users/navbar.html' %}
{% block content %}
    <h1>{{ task.title }}</h1>
    <details>
        <summary>Pokaż szczegóły zadania</summary>
        <p>Opis: {{ task.description }}</p>
        <p>Utworzono: {{ task.created_at }}</p>
        <p>Utworzone przez: {{ task.created_by }}</p>
        {% if task.user_story %}
            <p>Historia użytkownika: {{ task.user_story }}</p>
        {% endif %}
        {% if task.sprint %}
            <p>Sprint: {{ task.sprint }}</p>
        {% endif %}
    </details>

    {% if form %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% endif %}

    <a href="{% url 'my_tasks_page' %}">Return to the Task list</a>
    <br>

     {% if assigned_users %}
        <h3>Sprint Users:</h3>
        <ul>
     {% for user in assigned_users %}
         <li>{{ user.username }}</li>
     {% endfor %}
        </ul>
    {% else %}
        <p> No sprint USers.</p>
    {% endif %}

    <br>

    {% if task.estimations %}
         <p>{{ task.estimations.all }}</p>
        {% for estimation in task.estimations.all %}
            <li>{{ estimation.estimated_by.get_full_name }}: {{ estimation.get_estimation_display }}</li>
        {% endfor %}

    {% else %}
        <p>No estimation yet.</p>
    {% endif %}

    {% if estimation_ended %}
        <p>Estimation completed. The average estimation : {{ average_estimation }}</p>
    {% endif %}

    <a href="{% url 'estimate-task-create' task.pk %}">Create New Estimation</a>
{% endblock %}

tasks/templates/tasks/tasks_delete_page.html
{%  extends 'users/navbar.html'  %}
{%  block content%}
    <div class="container">
        <h1>       Deleting a task </h1>
        <p>  Are You sure U want to delete that  task </p>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            <br>
            <button type="submit"> Delete task    </button>
        </form>
        <a href="{%  url 'user_logout' %}"> </a>
        <a href="{% url 'my_tasks_page'    %}"> Return to My Tasks</a>
    </div>
{% endblock %}

tasks/templates/tasks/tasks_inside_page.html
<h1>  page with info about the task and options on the left . navbar will be imported soon </h1>

tasks/templates/tasks/tasks_main_page.html
{% extends 'users/navbar.html' %}
{% block content %}
    <h1> Tasks main page </h1>
    <a href="{%  url '' %}"> Task name </a>
    <br><br>
    <a href="{%  url '' %}"> Task description </a>
    <br><br>
    <a href="{%  url '' %}"> Sprint connected </a>
    <br><br>
    <a href="{%  url '' %}"> Add task </a>
    <br><br>
    <a href="{%  url 'my_tasks_page' %}"> View Tasks </a>
    <br><br>
    <a href="{%  url 'tasks_update_page' %}"> Update Tasks </a>
{% endblock %}

tasks/templates/tasks/tasks_update_page.html
{%  extends 'users/navbar.html'  %}
{%  block content%}
    <div class="container">
        <h1> Updating task the task </h1>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{UpdateTaskForm.as_p}}
            <br>
            <button type="submit"> Update task    </button>
        </form>
        <a href="{%  url 'user_logout' %}"> </a>
    </div>
{% endblock %}